source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/llnw/PodSpecs.git'

platform :ios, '8.0'

xcodeproj 'SampleApplication', 'Coverage' => :debug

pod 'LimelightVideoKit'

# Remove 64-bit build architecture from Pods targets
post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |configuration|
      target.build_settings(configuration.name)['ARCHS'] = '$(ARCHS_STANDARD_32_BIT)'
    end
  end
end
